-- MySQL Script generated by MySQL Workbench
-- Thu Dec  7 17:41:31 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema hallfit
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema hallfit
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `hallfit` DEFAULT CHARACTER SET utf8 ;
USE `hallfit` ;

-- -----------------------------------------------------
-- Table `hallfit`.`avaliador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hallfit`.`avaliador` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `login` VARCHAR(45) NULL,
  `senha` VARCHAR(100) NULL,
  `tipo` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hallfit`.`aluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hallfit`.`aluno` (
  `id` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `data_nascimento` DATE NULL,
  `objetivo` VARCHAR(45) NULL,
  `matricula` INT NULL AUTO_INCREMENT,
  `fumante` TINYINT NULL,
  `problema_coluna` TINYINT NULL,
  `pratica_atvfisica` TINYINT NULL,
  `comorbidade` TINYINT NULL,
  `alunocol` VARCHAR(45) NULL,
  `foto` VARCHAR(45) NULL,
  `objetivo` TINYTEXT NULL,
  `frequencia` TEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hallfit`.`avaliacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hallfit`.`avaliacao` (
  `idavaliacao` INT NOT NULL AUTO_INCREMENT,
  `altura` VARCHAR(45) NULL,
  `peso` VARCHAR(45) NULL,
  `percentual_gordura` VARCHAR(45) NULL,
  `massa_muscular` VARCHAR(45) NULL,
  `condicao_fisica` VARCHAR(45) NULL,
  `coxa_esq` VARCHAR(45) NULL,
  `coxa_dir` VARCHAR(45) NULL,
  `biceps_esq` VARCHAR(45) NULL,
  `biceps_dir` VARCHAR(45) NULL,
  `torax` VARCHAR(45) NULL,
  `abdomen` VARCHAR(45) NULL,
  `costas` VARCHAR(45) NULL,
  `ombro` VARCHAR(45) NULL,
  `avaliador_id` INT NOT NULL,
  `aluno_id` INT NOT NULL,
  PRIMARY KEY (`idavaliacao`, `avaliador_id`, `aluno_id`),
  INDEX `fk_avaliacao_avaliador1_idx` (`avaliador_id` ASC),
  INDEX `fk_avaliacao_aluno1_idx` (`aluno_id` ASC),
  CONSTRAINT `fk_avaliacao_avaliador1`
    FOREIGN KEY (`avaliador_id`)
    REFERENCES `hallfit`.`avaliador` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_avaliacao_aluno1`
    FOREIGN KEY (`aluno_id`)
    REFERENCES `hallfit`.`aluno` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hallfit`.`aluno_has_avaliador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hallfit`.`aluno_has_avaliador` (
  `aluno_id` INT NOT NULL,
  `avaliador_id` INT NOT NULL,
  PRIMARY KEY (`aluno_id`, `avaliador_id`),
  INDEX `fk_aluno_has_avaliador_avaliador1_idx` (`avaliador_id` ASC),
  INDEX `fk_aluno_has_avaliador_aluno1_idx` (`aluno_id` ASC),
  CONSTRAINT `fk_aluno_has_avaliador_aluno1`
    FOREIGN KEY (`aluno_id`)
    REFERENCES `hallfit`.`aluno` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_aluno_has_avaliador_avaliador1`
    FOREIGN KEY (`avaliador_id`)
    REFERENCES `hallfit`.`avaliador` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
